name: Dashboard Update
on:
  pull_request:
  push:
    branches:
      - master
jobs:
  run:
    runs-on: ubuntu-latest
    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      REACT_APP_UNSPLASH_API_KEY: ${{ secrets.UNSPLASH_API_KEY }}
      CI: false
    steps:
        - uses: actions/checkout@v3

        - name: Configure AWS Credentials
          uses: aws-actions/configure-aws-credentials@v1
          with:
            aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
            aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
            aws-region: eu-west-3
        - name: Build React App
          run: npm install && npm run build
        - name: Deploy app build to s3 bucket
          run: aws s3 sync ./build/ s3://oscarmpdgallery --delete